// Code generated by entc, DO NOT EDIT.

package ent

import (
	"gin-ent/ent/category"
	"gin-ent/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescCode is the schema descriptor for code field.
	categoryDescCode := categoryFields[1].Descriptor()
	// category.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	category.CodeValidator = categoryDescCode.Validators[0].(func(string) error)
}
